export const environment = {
  production: true,
  oidcRedirectRoot: "https://cdn-dev.gsu.edu/cm/#/login",
  loginConfig: {
    authority: 'https://idp-d.gsu.edu/',                 // Auth server URI
    client_id: '@!18B2.0B8D.E469.44F9!0001!B391.7220!0008!8F37.82D6.B56D.B3F4', // Client ID generated by auth server
    redirect_uri: this.oidcRedirectRoot + "?mode=redirect",            // Must also be set in auth server settings for this client
    silent_redirect_uri: this.oidcRedirectRoot + "?mode=silent",              // Must also be set in auth server settings for this client
    popup_redirect_uri: this.oidcRedirectRoot + "?mode=popup",               // Must also be set in auth server settings for this client
    post_logout_redirect_uri: this.oidcRedirectRoot + "?mode=logout",              // Must also be set in auth server settings for this client
    scope: "email gsupersonpantherid gsUser openid profile"
  }
};