const oidcRedirectRoot = "http://localhost:8100/#/login";
export const environment = {
    production: true,
    loginConfig: {
        authority: 'https://idp-d.gsu.edu/',                 // Auth server URI
        client_id: '@!18B2.0B8D.E469.44F9!0001!B391.7220!0008!8F37.82D6.B56D.B3F4', // Client ID generated by auth server
        redirect_uri: oidcRedirectRoot + "?mode=redirect",            // Must also be set in auth server settings for client
        silent_redirect_uri: oidcRedirectRoot + "?mode=silent",              // Must also be set in auth server settings for client
        popup_redirect_uri: oidcRedirectRoot + "?mode=popup",               // Must also be set in auth server settings for client
        post_logout_redirect_uri: oidcRedirectRoot + "?mode=logout",              // Must also be set in auth server settings for client
        scope: "email gsupersonpantherid gsUser openid profile"
    }
};